### ISSUE TITLE
SBOL generation error with reverse-comp

### ISSUE THREAD

**Issue by dany-fu** [hicsail/constellation-js#98]
The GOLDBAR:
`one-or-more((Cello_promoter then zero-or-one(Cello_promoter) then Cello_ribozyme then Cello_RBS then Cello_CDS then Cello_terminator) or reverse-comp(Cello_promoter then zero-or-one(Cello_promoter) then Cello_ribozyme then Cello_RBS then Cello_CDS then Cello_terminator))` 

Behavior:
Graph and enumerations are generated, but the SBOL file is `[undefined]` 

Error stack:
```
TypeError: Cannot read property 'combDV' of undefined
    at sbolGeneration.makeSBOLFromStack (/Users/danyfu/Documents/bio-circuit/constellation-js/lib/sbol.js:476:34)
    at generateCombinatorialSBOL (/Users/danyfu/Documents/bio-circuit/constellation-js/lib/edgeSBOL.js:333:11)
    at Object.goldbar (/Users/danyfu/Documents/bio-circuit/constellation-js/lib/constellation.js:96:19)
    at /Users/danyfu/Documents/bio-circuit/constellation-js/demos/server.js:48:32
    at Layer.handle [as handle_request] (/Users/danyfu/Documents/bio-circuit/constellation-js/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/danyfu/Documents/bio-circuit/constellation-js/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/danyfu/Documents/bio-circuit/constellation-js/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/danyfu/Documents/bio-circuit/constellation-js/node_modules/express/lib/router/layer.js:95:5)
    at /Users/danyfu/Documents/bio-circuit/constellation-js/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/danyfu/Documents/bio-circuit/constellation-js/node_modules/express/lib/router/index.js:335:12)
```

**Comment by dany-fu** [comment]
No error if the `zero-or-one(Cello_promoter)` portion of the specification is removed
